[all:vars]
ansible_user=isaac

[ubuntu]
ubuntu_host ansible_host=192.168.56.108

[centos]
centos_host ansible_host=192.168.56.118 ansible_user=jhonisaacalegre

[db_servers]
ubuntu_host
centos_host

[monitoring_server]
ubuntu_host

[monitored_nodes:children]
db_servers
monitoring_server
